// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNdlEnBQ2C6pIvCQ1RUTnscP3ioMuatSA',
    appId: '1:985165007111:web:09e274af3d64754b1edda2',
    messagingSenderId: '985165007111',
    projectId: 'trial-b861f',
    authDomain: 'trial-b861f.firebaseapp.com',
    storageBucket: 'trial-b861f.appspot.com',
    measurementId: 'G-ZH73N313QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3Dqjrx7eBdbEf174tqnB3g555PLozJg',
    appId: '1:985165007111:android:b83899c54d6e4bef1edda2',
    messagingSenderId: '985165007111',
    projectId: 'trial-b861f',
    storageBucket: 'trial-b861f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDnxA3g4mjyCEh4yvuT7It6C9PgQaebeA',
    appId: '1:985165007111:ios:5b401a6591b0d4031edda2',
    messagingSenderId: '985165007111',
    projectId: 'trial-b861f',
    storageBucket: 'trial-b861f.appspot.com',
    iosBundleId: 'com.example.spesoAst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDnxA3g4mjyCEh4yvuT7It6C9PgQaebeA',
    appId: '1:985165007111:ios:f2e2afe421d57c3a1edda2',
    messagingSenderId: '985165007111',
    projectId: 'trial-b861f',
    storageBucket: 'trial-b861f.appspot.com',
    iosBundleId: 'com.example.spesoAst.RunnerTests',
  );
}
